### ISSUE TITLE
Update test link

### ISSUE THREAD

**Issue by lino-levan** [SkyStar-modules/denoFFMPEG#15]
The link in `httpFile_test.ts` is dead. We should replace it with another link, preferably one that is alive. Does anyone have the original video, or does any video work for this?

https://github.com/SkyStar-modules/denoFFMPEG/blob/7e311c9a343d28704645f8ab5f43234d79da5a98/tests/httpFile_test.ts#L4

**Comment by MierenManz** [comment]
It works with any URL that has a content type of `video/*` as long as you have that decoder in your build of ffmpeg.

For the test any URL of `video/mp4` should be fine

**Comment by lino-levan** [comment]
Cool, I will update the link in #14 and that should fix the CI issues.

**Comment by MierenManz** [comment]
You can create a new pr for it if you want to. But this is fine aswell

**Comment by lino-levan** [comment]
Closed by #14
