### ISSUE TITLE
`save()` returns a Access Denied error 

### ISSUE THREAD

**Issue by CompeyDev** [SkyStar-modules/denoFFMPEG#16]
I'm not highly experience with deno myself (I've used node practically my entire life) - more or less using it for a joke project, but based on my existing knowledge, I'm guessing that the below access denied error is occurring at the save function. 

![image](https://user-images.githubusercontent.com/74418041/219111448-dffab4e6-cd26-458c-8595-08a300f2c804.png)

Attempted to run as root, still does not fix the issue. I am not sure whether this occurs due to the `ffmepgDir` option or the `save` method call as these are the only two filesystem related operations. Furthermore, the docs are incredibly minimal; unsure as to what `ffmpegDir` even is. Is it a temporary operation directory of sorts? If so, is it intended to be empty? 

Following is reproducible code:

```ts
const renderProcess = ffmpeg({
    input: "./assets/input.mp4",
    ffmpegDir: "./data",
});

await renderProcess
    .videoFilters({
        filterName: "drawtext",
        options: {
            textfile: "./contents.txt",
            x: "(w-tw)/2",
            y: "h-t*100",
            fontcolor: "white",
            fontsize: 90,
        },
    })
    .videoBitrate("1000k")
    .save("./output.mp4");
```

**Comment by MierenManz** [comment]
ffmpegDir is not the correct name. It basically refers to the path of the ffmpeg binary. Which should be picked up automatically (I think) so if it's in your PATH then it should just be empty.

**Comment by CompeyDev** [comment]
> `ffmpegDir` is not the correct name for what it does (my mistake). It basically refers to the path of the ffmpeg binary. Which should be picked up automatically (I think) so if it's in your PATH then it should just be empty.

Ah that makes sense, thanks! But even without the parameter, this exact same error occurs. I created a minimal test system and looks like none of Deno's FS APIs can access the filesystem, which is odd as this works perfectly fine in Node.

**Comment by CompeyDev** [comment]
@MierenManz Bumping so you see this. ^

**Comment by MierenManz** [comment]
> I created a minimal test system and looks like none of Deno's FS APIs can access the filesystem, which is odd as this works perfectly fine in Node.

That is extremely weird. This worked on windows and on Linux for me as usual. 
Are you trying to run it under wsl?

**Comment by CompeyDev** [comment]
Running it under Windows without WSL. Tested on Linux too - facing the same issue. In both the cases, the output directory can be written to i.e., permissions are alright.

**Comment by MierenManz** [comment]
Then I have no idea what is going on here. Please add me on discord: Bubbles#3553 so that we can investigate with some more ease :sweat_smile:

**Comment by CompeyDev** [comment]
Nah, that's fine - I abandoned the project anyway. Thanks for all the help though (:
